### ISSUE TITLE
Getting Cors error in local and live both - React js

### ISSUE THREAD

**Issue by rranadigimonksolutions** [isaacdarcilla/select-philippines-address#8]
Hy,

I'm getting cors error when i call any regions , provinces , cities or barangays function.

see attached screen shot.

![Screenshot_1](https://user-images.githubusercontent.com/78405229/124556894-8089cb80-de56-11eb-8169-57963db20e0b.png)

**Comment by bushidosnap** [comment]
how to solve this one? I'm having the same issue
